name: AWS S3 + CloudFront Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v1
      - name: Install npm dependencies
        run: npm i
      - name: Build application
        run: npm run build
      - name: Move new files to S3 and invalidate cloud front distribution cache
        run: ./.github/scripts/aws.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
